In [2]:
from monomial_neural_network import *
from experiment import *

In [14]:
d = 2 # input data dimension
teacher_k = [10] # teacher model hidden layer sizes - 3 layers with increasing number of neurons
# teacher_k = [10] # teacher model hidden layer sizes - 1 layer with 10 neurons

teacher_model = generate_teacher_model(d, teacher_k)
print(teacher_model)

n = 1000 # number of data points
# same data dimension d as before

data = generate_data(n, d, teacher_model)

# verify that the data is generated correctly
print(data[0][0], data[1][0], teacher_model.evaluate(data[0][0]))

student_k = [10] # student model hidden layer sizes - 2 layers with increasing number of neurons
student_model = generate_student_model(d, student_k)



MonomialNeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=2, out_features=10, bias=False)
    (1): Monomial()
    (2): Linear(in_features=10, out_features=1, bias=False)
  )
)
tensor([0.0379, 1.7944]) tensor([19.8245]) tensor([19.8245])


In [15]:
# train the student
student_model, losses = train(
    model = student_model, 
    x_train = data[0], 
    y_train= data[1], 
    num_epochs = 5000, 
    lr = 1e-3
    )

starting training
Epoch [0/1000], Loss: 177.40355
Epoch [100/1000], Loss: 144.24333
Epoch [200/1000], Loss: 114.59195
Epoch [300/1000], Loss: 88.33173
Epoch [400/1000], Loss: 65.43103
Epoch [500/1000], Loss: 45.93804
Epoch [600/1000], Loss: 29.96908
Epoch [700/1000], Loss: 17.68212
Epoch [800/1000], Loss: 9.20195
Epoch [900/1000], Loss: 4.32761

Training Complete


In [13]:
# lets look at the weight matrices
student_w = student_model.layers[0].weight.detach().numpy()
teacher_w = teacher_model.layers[0].weight.detach().numpy()
print(student_w)
print(teacher_w)
A = student_w.T @ student_w
Astar = teacher_w.T @ teacher_w
print(A)
eigA, eigvecA = np.linalg.eig(A)
print(eigA)
print(Astar)
eigAstar, eigvecAstar = np.linalg.eig(Astar)
print(eigAstar)


[[ 0.220054    1.0855627 ]
 [ 0.750685   -0.32780513]
 [ 0.19331051  0.03366488]
 [-0.78595996  0.10697188]
 [ 0.07561972 -2.1309059 ]
 [-1.3225788  -0.33739987]
 [-0.8916763   0.28893992]
 [ 0.49563265 -0.57778037]
 [-1.0335886   0.8575047 ]
 [-0.40979555  1.1342314 ]]
[[-0.47236213 -1.1775715 ]
 [-0.270607    0.46297172]
 [-0.19631551  0.8978002 ]
 [ 0.6561154   0.06425652]
 [ 0.13269465  0.46593502]
 [ 0.40956682 -0.4293697 ]
 [ 0.29044786  0.13869771]
 [ 0.40141216 -0.1226082 ]
 [-0.17261752 -1.4038088 ]
 [ 0.2946981   0.4992285 ]]
[[ 5.298963  -1.6947823]
 [-1.6947823  8.392189 ]]
[4.5511703 9.139982 ]
[[1.3128697  0.56334764]
 [0.56334764 5.0668235 ]]
[1.230152  5.1495414]
